spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
